receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  elasticsearch:
    endpoints:
      - http://elasticsearch:9200
    user: elastic
    password: ${env:ELASTIC_PASSWORD}
    flush:
      interval: 1s
    logs_index: otel-logs-nanos
    traces_index: otel-traces
  otlphttp/elastic-apm:
    endpoint: http://apm-server:8200
    headers:
      Authorization: "Bearer ${env:ELASTIC_APM_SECRET_TOKEN}"
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/elastic-apm, otlp/jaeger, zipkin]
    logs:
      receivers: [otlp]
      exporters: [elasticsearch]