apiVersion: 1

datasources:
  - name: Elasticsearch Logs
    uid: elasticsearch-logs
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: otel-logs-nanos*
    basicAuth: true
    basicAuthUser: elastic
    secureJsonData:
      basicAuthPassword: "$__env{ELASTIC_PASSWORD}"
    jsonData:
      esVersion: 8
      timeField: "@timestamp"

  - name: Jaeger
    uid: jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686